"""Update the Supplementary Information to match executed revision-3 analyses."""
from pathlib import Path

root = Path(__file__).resolve().parents[3]
path = root / "total/rebuild_2026/manuscript/Supplementary_Information.md"
s = path.read_text(encoding="utf-8")

def one(old, new):
    global s
    n = s.count(old)
    if n != 1:
        raise AssertionError((n, old[:100]))
    s = s.replace(old, new, 1)

one("GSE206710 supplies three-donor single-cell stage summaries.",
    "GSE206710 supplies 12 sample–stage aggregates nested within three donors; donor D1 contributes more than one library in some stages. The plotted unit IDs now use unique sample–stage labels. The normal spline combines these 12 units with eight GSE195812 pooled FACS stage libraries, for 20 measured units; its R² is an in-sample description, not an analysis of 20 independent donors.")
one("Twenty measured stage units from GSE195812 and GSE206710 define the observed reference-domain range.",
    "The 20 measured units (eight pooled FACS stage libraries and 12 sample–stage aggregates from three donors) define the observed reference-domain range.")
one("The primary residual is observed minus the developmental spline fitted within the 1,309-patient cohort.",
    "The primary residual is observed minus the developmental spline fitted within the 1,309-patient cohort. CD34, LYL1 and CD1A comprise a developmental-expression proxy: their normal-stage directionality supports its interpretation, but driver-related changes in these genes could change the score without changing a cell's true maturation state. The residual is not an absolute normal-cell distance.")
one("Small subtypes retain their individual points and appropriately wide intervals.",
    "Small subtypes retain their individual points and appropriately wide intervals. Figure 3D summarizes the median of residuals from the model without subtype. Figure 3E is a coefficient from a separate joint model, referenced to the equal-weighted mean of 17 subtype intercepts after conditioning on a shared spline. These estimands need not have identical signs; TLX1, HOXA9 TCR and NKX2-1 illustrate the distinction.")

anchor = "### Lim single-cell pseudobulk"
section = r'''### Post-review developmental-proxy and model-robustness analyses

All analyses in this section were executed on the existing 1,309 unique diagnostic patients; they are post-review, exploratory sensitivity analyses, not preregistered confirmatory tests or external replication. Full-precision patient and subtype outputs are in `data/source_data_rebuilt/revision3_robustness/`, generated by `code/revision3_reviewer_robustness.R` with its recorded R session. No subtype, sample or outcome was added to the primary cohort.

For subtype (s), we excluded every patient in (s), fitted the same three-degree-of-freedom natural spline in the remaining 16 subtypes, then predicted the held-out patients:

$$
R_i^{(-s)}=B_i-\widehat f_{-s}(D_i), \qquad i\in s.
$$

The training-coordinate range was checked for each held-out case. Neither BCL11B nor TLX3 had patients beyond its corresponding training range. BCL11B remained the lowest median (−2.22) and TLX3 the highest (+0.78); this removes self-influence on the fitted expectation but remains internal to the same cohort (Fig. 7A; Table S8A).

We also recalculated cohort-standardized expression scores after leaving out each original marker, with no re-selection of markers from leukemia outcomes:

$$
\begin{aligned}
D_{-\mathrm{CD34}}&=z(\mathrm{CD1A})-z(\mathrm{LYL1}),\\
D_{-\mathrm{LYL1}}&=z(\mathrm{CD1A})-z(\mathrm{CD34}),\\
D_{-\mathrm{CD1A}}&=-\tfrac12\{z(\mathrm{CD34})+z(\mathrm{LYL1})\}.
\end{aligned}
$$

An expanded sensitivity score averaged seven cortical-direction genes (CD1A, PTCRA, RAG1, RAG2, CD1B, LEF1, TRAC) and subtracted the mean of three early-direction genes (CD34, LYL1, MEF2C). The added markers had concordant directions in two available normal sources, a weaker eligibility standard than the frozen three-gene coordinate; SPI1 was intentionally excluded because it names a molecular subtype. All genes were retrieved as TMM log₂ counts per million from the original count matrix; the recalculated CD34 values agreed with the frozen patient table to <10⁻⁶. Each alternative score was refitted to balance with the same three-degree-of-freedom spline within the cohort. BCL11B ranked first or second most negative and TLX3 first or second most positive across these five score definitions, whereas ETP-like residuals and exact ranks changed (Fig. 7B; Table S8B).

For Figure 2F, the four regression specifications used the same 1,309 patients: author-assigned immunophenotype, developmental spline, 17-level molecular subtype, and their developmental-plus-subtype combination. Raw and adjusted R² are listed with model degrees of freedom in Table S8C. Repeated five-fold cross-validation used five subtype-stratified random splits (seed 20260926). Within each training fold, we recomputed the means and standard deviations of CD34, LYL1, CD1A, ZEB1 and ZEB2, then applied those training parameters to held-out patients before calculating score and balance; spline bases and coefficients were likewise learned from training data. The author-labelled immunophenotype has four common classes plus one singleton “Other” patient. That patient stayed in training for all models so the held-out immunophenotype factor level was defined; the common held-out denominator was 1,308 patients per repeat. The subtype increment after the developmental model was computed as both raw ΔR² and partial R²:

$$
R^2_{\mathrm{partial,subtype}\mid\mathrm{dev}}
=\frac{R^2_{\mathrm{combined}}-R^2_{\mathrm{dev}}}{1-R^2_{\mathrm{dev}}}=0.187.
$$

Three focused BCL11B-minus-comparator median-residual differences (ETP-like, SPI1, LMO2 γδ-like) were fixed for this response and received 3,000 within-group patient-bootstrap percentile intervals (seed 20260926). BCL11B minus ETP-like was −1.53 (95% CI, −2.32 to −0.67); SPI1 and LMO2 γδ-like comparisons spanned zero. We separately matched the 18 BCL11B patients one-to-one to ETP-like patients by nearest developmental coordinate, without replacement. Median and maximum absolute coordinate distances were 0.016 and 0.090. The matched-pair mean primary-residual difference was −1.92 (3,000-pair bootstrap 95% CI, −2.98 to −0.67; seed 20260927). Matching is a descriptive same-cohort sensitivity, not a causal comparison or external replication (Fig. 7D,E; Table S8D).

'''
if anchor not in s:
    raise AssertionError(anchor)
s = s.replace(anchor, section + anchor, 1)
one("The unit of the paired state analysis is a biological patient sample.",
    "The unit of the paired state analysis is a biological patient sample. ZBTB16 detection was an operational state label allowing within-patient paired pseudobulks under the frozen cell-count threshold; it is not asserted to be a validated developmental stage or an upstream regulator of ZEB expression.")
one("Figure S5 retains contact depth, separate locus measures, scATAC peak-set values and pooled GSE146901 loop rates.",
    "Figures S5 and S9 retain contact depth, separate locus measures, scATAC peak-set values and pooled GSE146901 loop rates. The former is the assay/QC audit; the latter preserves the eight-panel chromatin comparison formerly displayed as main Figure 7.")
one("These models do not demonstrate calibrated prediction, independent clinical utility or transportability.",
    "These models do not demonstrate calibrated prediction, independent clinical utility or transportability. We did not fit a penalized Cox replacement in this revision; EFS and OS remain exploratory because their rare-subtype coefficients were unstable.")

marker = "## Supplementary Tables S1–S7"
addition = '''## Supplementary Figure S9. Exploratory HiChIP chromatin context and cross-assay boundaries

**A,** Filtered-contact depth across ten usable HiChIP libraries. **B,C,** ZEB1 gene-body contacts and ZEB2/ZEB1 contact ratios. **D,** All three ETP libraries rank above all four non-ETP libraries for the ratio; exact two-sided P = 0.057 is the minimum possible with these group sizes. **E,** Paired ZEB1 and ZEB2 locus contacts. **F,** Promoter-window contacts. **G,** Pooled GSE146901 loop rates, which do not reproduce reciprocal polarity and are not patient-level independent replicates. **H,** Seven scATAC peak sets, with no independent replication of the HiChIP ratio. These data provide exploratory assay-specific context, not a replicated chromatin mechanism.

'''
if marker not in s:
    raise AssertionError(marker)
s = s.replace(marker, addition + "## Supplementary Tables S1–S8", 1)
one("*Supplementary_Tables_S1-S7.xlsx*", "*Supplementary_Tables_S1-S8.xlsx*")
s += "\n**Table S8. Developmental-proxy and BCL11B robustness.** Four sheets provide held-out subtype residuals, alternative-score ranks, raw/adjusted/cross-validated model R², and the three fixed pairwise plus developmental-matched BCL11B contrasts. Full-precision patient tables and executed code are in the source archive.\n"
path.write_text(s, encoding="utf-8")
print(path)
