"""Replace abbreviated legends with self-contained panel-by-panel captions."""
from pathlib import Path

root = Path(__file__).resolve().parents[3]
main = root / "total/rebuild_2026/manuscript/ZEB1_ZEB2_TALL_manuscript_polished.md"
supp = root / "total/rebuild_2026/manuscript/Supplementary_Information.md"

main_legends = r'''## Figure legends

**Figure 1. Normal human thymopoiesis establishes a stage-patterned ZEB1–ZEB2 expression axis.**
(**A**) UMAP of T-lineage cells in GSE195812, colored by the originating FACS-defined DN1, DN2, DN3, immature single-positive (ISP), double-positive (DP) or single-positive stage. Each point is a cell; the FACS libraries pooled material from six donors, so the point count is not a donor-level sample size. (**B**) The same embedding colored by detectable ZEB1 log-transformed expression; grey cells have no displayed signal. This panel localizes expression within the existing embedding and is not a differential-expression test. (**C**) ZEB2 expression on the identical cells and coordinates, permitting a direct visual comparison with panel B. (**D**) Complete stage-ordered ZEB1, ZEB2 and balance tracks in GSE142522, GSE195812, GSE206710 and Park/HTA. Each source retains its reported stage nomenclature and is standardized within atlas for display; the blue–neutral–orange scale is centered at zero. Numbers in the balance row are the source-standardized ZEB1-minus-ZEB2 values. The ISP decline and later CD8 single-positive ZEB2 recovery are shown rather than removed by monotonic smoothing. (**E**) ZEB1 expression in matched DN and CD4 single-positive donor-stage aggregates from 15 eligible Park/HTA donors; each line connects the same donor, and the donor is the independent unit. (**F**) Early-to-cortical expression direction of CD34, LYL1 and CD1A in the four normal resources. Minus denotes higher early expression, plus higher cortical/DP expression, and NA an unavailable contrast. These three genes form the developmental-expression score; ZEB1, ZEB2 and LMO2 are absent from it. Full stage data, marker eligibility and missingness are in Supplementary Figure S1.

**Figure 2. The 1,309-patient molecular-subtype landscape of ZEB-family expression.**
(**A**) Alluvial map from author-assigned immunophenotype to 17 molecular subtypes. Flow thickness encodes patient count; all 47 observed category transitions are retained. BCL11B, ETP-like and TLX3 transitions are highlighted, while other flows are neutral to preserve their counts without giving each subtype another saturated color. The author immunophenotype contains four common classes and a singleton Other category. (**B**) Median ZEB1, ZEB2, LMO2, ZEB balance and three-gene developmental-expression score for each of the 17 subtypes, with the subtype patient count printed at right. Each metric is standardized across the subtype medians for this heatmap only; color is centered at zero and clipped visually at ±2 for legibility. It is not the patient-level normalization used in the models. (**C**) All 1,309 patient-level ZEB balance values, ordered by the same molecular-subtype sequence as panels B and D. Dots are patients, dark bars indicate interquartile ranges and diamonds indicate medians; the zero line marks equal cohort-standardized ZEB1 and ZEB2 expression. (**D**) Median three-gene coordinate for each subtype on the same order; connecting stems emphasize location relative to zero, not a temporal trajectory. (**E**) Patient-level ZEB1 and ZEB2 cohort z scores. The diagonal denotes equal standardized expression, and BCL11B, ETP-like and TLX3 are highlighted against all other patients. (**F**) In-sample raw R² for author immunophenotype, a three-degree-of-freedom developmental spline, 17-subtype indicators and the spline-plus-subtype model. The plotted values are descriptive because model degrees of freedom differ; adjusted and held-out R² for these same models are compared in Figure 7C and Table S8C. No R² bar is a causal variance partition.

**Figure 3. Cohort-internal developmental-expression adjustment and the 17-subtype residual landscape.**
(**A**) Normal-thymus reference spline of ZEB balance on the three-gene coordinate. The 20 measured units are eight pooled FACS stage libraries from GSE195812 and 12 sample–stage aggregates nested within three GSE206710 donors; colors denote broad early, cortical/DP and later stages. The in-sample R² of 0.73 describes this reference shape and is not based on 20 independent donors. (**B**) All 1,309 diagnostic patients against a separate natural spline fitted within the leukemia cohort. The black curve is the primary cohort-internal expected balance; BCL11B, ETP-like and TLX3 patients are highlighted, and other patients remain visible in grey. The normal reference is not used to calculate this curve. (**C**) Individual observed-minus-cohort-expected residuals for all 17 subtypes; dots retain patients and diamonds mark subtype medians. The zero line represents the cohort-fitted expectation, not a normal-cell threshold. (**D**) Median residuals and percentile 95% confidence intervals from 3,000 subtype-stratified patient bootstraps. The developmental-only spline was refitted in every replicate; rows share the subtype order with panel E. (**E**) Coefficients from a separate spline-plus-subtype model using sum-to-zero contrasts, referenced to the equal-weighted mean of subtype intercepts. Bars are bootstrap 95% intervals, filled points have HC3 two-sided P values surviving Benjamini–Hochberg correction across 17 subtype effects, and open points do not. A coefficient can differ in magnitude or sign from the panel-D median because the two estimands use different baselines and summaries. (**F**) Selected subtype medians under the primary cohort-internal residual and a separately standardized normal-reference projection. Their magnitudes are not interchangeable; 14 of 18 BCL11B coordinates lie beyond the measured normal-reference domain. Full patient values and extrapolation boundaries appear in Supplementary Figure S2 and Table S3.

**Figure 4. BCL11B-associated ZEB2 dominance across primary-cohort patients and a lesion-defined case series.**
(**A**) Median cohort-internal developmental-expression residual for each of 17 molecular subtypes, with BCL11B highlighted at −1.76 among 18 assigned patients. This is a descriptive rank; Figure 7E tests fixed contrasts and shows that differences from SPI1 and LMO2 gamma-delta-like are uncertain. (**B**) TMM-normalized log₂ counts per million for ZEB1 and ZEB2 in each of the 18 BCL11B-subtype diagnostic patients. Connected endpoints belong to the same patient; no between-patient pairing is implied. (**C**) Complete GSE162280 lesion-defined 12-case matrix. Each row is one case; columns show rearrangement class and partner, reported AML/MPAL/ETP-ALL or unspecified phenotype, ZEB1 and ZEB2 CPM, and the log₂ ZEB1/ZEB2 ratio. A ratio below zero indicates ZEB2 dominance. The five ZEB2-fusion, five ARID1B-enhancer and two CDK6-enhancer cases are all retained. (**D**) Cross-tabulation of lesion class against reported phenotype in these 12 cases. Cell numbers are cases, not RNA libraries or technical replicates; the mixed diagnoses limit comparison with ordinary T-ALL. (**E**) Median and observed range of the case-level log₂ ratio within each lesion class. Labels give the number ZEB2-dominant out of the group denominator (5/5, 5/5, 2/2); the zero line is equal ZEB1 and ZEB2 expression. (**F**) Recorded genomic lesion flags for the 18 primary-cohort BCL11B patients, ordered by their balance. Filled cells indicate recorded flags and may overlap within a patient; blank cells must not be interpreted as proof that a lesion is absent. The primary cohort and external lesion-defined series are distinct populations. Full case identifiers, depth and counts appear in Supplementary Figure S6 and Table S6.

**Figure 5. Independent bulk RNA tests the narrower ETP/non-ETP expression contrast.**
(**A**) Cohort-standardized ZEB1-minus-ZEB2 balance in GSE146901, with individual RNA samples overlaid on median and interquartile summaries: eight ETP T-ALL, ten non-ETP T-ALL and four healthy peripheral T-cell controls. The two-sided ETP versus non-ETP Mann–Whitney P value is 0.012. Peripheral T cells are shown for context and are not normal thymocytes. (**B**) Raw-expression sensitivity on the same 22 samples using log₂(ZEB1/ZEB2), rather than the standardized balance; the ETP versus non-ETP Mann–Whitney P value is 0.016. The ratio and balance have different scales and should not be numerically pooled. (**C**) Within-sample ZEB1 and ZEB2 expression for each leukemia case; connected points identify the two genes measured in the same RNA sample, and the groups are displayed separately. (**D**) All 22 samples and four metrics—ZEB1, ZEB2, balance and ratio—in one matrix. Each row is standardized separately for display, with blue below and orange above the row mean; the top annotation identifies ETP, non-ETP and peripheral T controls. (**E**) ETP-minus-non-ETP median difference for each original metric with its two-sided Mann–Whitney P value. The two composite metrics cross the nominal 0.05 threshold, while separate ZEB1 and ZEB2 comparisons do not; no clinical classifier is inferred. (**F**) Scoped historical four-cohort meta-analytic context for three TLX/TAL expression contrasts, shown as pooled Hedges g and 95% intervals under DerSimonian–Laird and REML/modified Hartung–Knapp methods. The latter interval for TLX-class ZEB1 includes zero. Study-level effects and leave-one-cohort-out analyses are in Supplementary Figure S7; historical class labels do not recapitulate the modern 17 subtypes.

**Figure 6. Patient-paired malignant-cell states and exploratory baseline treatment-response association.**
(**A**) ZBTB16-positive versus ZBTB16-negative malignant-cell pseudobulk balance from 41 eligible paired Day-0 biological samples in the Lim resource. Each point is one patient-level pair, colors denote induction-response groups, and the dashed identity line indicates no within-patient difference. ZBTB16 detection is an operational cell-state label, not an established developmental stage. (**B**) Signed positive-minus-negative balance difference for the same 41 pairs, ordered from most negative to most positive; the zero line makes heterogeneous patient responses visible. (**C**) Mean paired positive-minus-negative differences for ZEB1, ZEB2, LMO2 and balance with 95% percentile intervals from patient bootstrap resampling. Bars describe mean differences, not gene-level differential-expression significance. (**D**) Fraction of ZBTB16-positive malignant cells versus each patient's paired balance difference, to show that state contrast is not simply a function of the positive-cell fraction. (**E**) Day-0 whole-malignant pseudobulk balance in 19 induction-failure and 35 responsive patients; dots are biological patients, boxes show interquartile ranges, and the printed Welch P = 0.0050 is an unadjusted comparison. (**F**) Induction-failure-minus-responsive mean differences and bootstrap 95% intervals for the four metrics. Printed Hedges g values are standardized point estimates only; the adjacent bars are intervals for mean differences, not for g. (**G**) The baseline balance mean difference in the combined, discovery and extension subsets, each with patient-bootstrap 95% intervals. The extension interval includes zero. (**H**) Separate unadjusted, broad-subtype, age and ETP one-covariate sensitivity coefficients; these are not sequentially cumulative models, and the ETP-adjusted interval crosses zero. (**I**) ETP-status and broad genomic-class composition by induction group, using patient proportions. This imbalance limits a claim of independent response prediction. The 54 baseline patients, 41 state pairs and 12 Day-0/Day-28 pairs are distinct eligibility denominators; Supplementary Figure S3 documents the flow and the Day-28 null result.

**Figure 7. Developmental-expression proxy robustness and the limits of external support.**
(**A**) All 17 subtype median residuals from the primary cohort-fitted spline (grey) and a leave-one-subtype-out spline (dark points). For each tested subtype, the expected-balance curve was fitted in patients from the other 16 subtypes before predicting its held-out patients. BCL11B (purple) remained lowest and TLX3 (orange) highest; no patient in either group lay outside its training coordinate range. The 17 analyses remain within the same 1,309-patient cohort. (**B**) BCL11B, ETP-like and TLX3 median residuals after three leave-one-marker-out developmental scores and an expanded early/cortical expression score, each with a refitted cohort spline. All five definitions were tested on the same patients. BCL11B and TLX3 rank first or second in their respective directions, but exact ranks and ETP-like values vary; no displayed point has a confidence interval. (**C**) Adjusted R² and mean held-out R² across five repeated, subtype-stratified five-fold splits for the four Figure-2F models. Standardization means and standard deviations were learned in each training fold; frozen TMM preprocessing and the singleton immunophenotype Other patient, retained in every training fold, limit the held-out denominator to 1,308 patients per repeat. CV tests within-cohort regression performance, not external transportability. (**D**) Eighteen BCL11B cases matched one-to-one without replacement to ETP-like cases by nearest developmental coordinate (median absolute distance 0.016, maximum 0.090). Lines connect matched pairs; the printed −1.92 mean paired residual difference and its −2.98 to −0.67 interval arise from 3,000 pair bootstraps. Matching is descriptive, not causal. (**E**) Fixed BCL11B-minus-ETP-like, -SPI1 and -LMO2 gamma-delta-like contrasts in median primary residual. Points are differences; bars are 3,000 within-group patient-bootstrap percentile 95% intervals. Only the ETP-like interval excludes zero, so “most negative” denotes observed rank rather than proof of separation from every subtype. (**F**) Evidence-scope summary: the primary 17-subtype architecture and sensitivity analyses are cohort-internal; external bulk, single-cell and lesion-defined series test narrower contrasts; complete external residual-ranking replication and a chromatin mechanism remain unestablished. Detailed definitions and full precision are in Supplementary Methods and Table S8; exploratory chromatin measurements are in Supplementary Figures S5 and S9.

---

'''

s = main.read_text(encoding="utf-8")
main_legends = main_legends.replace(
    "Alluvial map from author-assigned immunophenotype to 17 molecular subtypes. Flow thickness encodes patient count; all 47 observed category transitions are retained. BCL11B, ETP-like and TLX3 transitions are highlighted, while other flows are neutral to preserve their counts without giving each subtype another saturated color. The author immunophenotype contains four common classes and a singleton Other category.",
    "Count matrix crossing author-assigned immunophenotype with all 17 molecular subtypes. Each printed integer is a patient count; all 47 nonzero combinations are shown, zero cells are blank, and teal intensity represents the fraction of that subtype assigned to the indicated immunophenotype. The author immunophenotype contains four common classes and a singleton Other category. Rows align exactly with panels B and C, avoiding the need to trace intersecting flows."
)
main_legends = main_legends.replace(
    "Complete GSE162280 lesion-defined 12-case matrix. Each row is one case; columns show rearrangement class and partner, reported AML/MPAL/ETP-ALL or unspecified phenotype, ZEB1 and ZEB2 CPM, and the log₂ ZEB1/ZEB2 ratio. A ratio below zero indicates ZEB2 dominance. The five ZEB2-fusion, five ARID1B-enhancer and two CDK6-enhancer cases are all retained.",
    "Case-level dumbbell plot for all 12 GSE162280 BCL11B-rearranged leukemias. Each horizontal segment joins ZEB1 (red) and ZEB2 (blue) CPM from the same case on a logarithmic expression axis. Case labels give the reported AML, MPAL, ETP-ALL or unspecified phenotype; symbols distinguish five ZEB2-fusion, five ARID1B-enhancer and two CDK6-enhancer cases. The right-hand label is the case-level log₂(ZEB1/ZEB2) ratio; every ratio is below zero. Exact CPM and partner annotations remain in Table S6."
)
main_legends = main_legends.replace(
    "Evidence-scope summary: the primary 17-subtype architecture and sensitivity analyses are cohort-internal; external bulk, single-cell and lesion-defined series test narrower contrasts; complete external residual-ranking replication and a chromatin mechanism remain unestablished. Detailed definitions and full precision are in Supplementary Methods and Table S8; exploratory chromatin measurements are in Supplementary Figures S5 and S9.",
    "Rank stability across the primary three-gene coordinate, three leave-one-marker-out coordinates and the expanded marker score. Each grey point is one of 17 molecular subtypes ordered by its median residual within that score definition (rank 1, most ZEB2-skewed; rank 17, most ZEB1-skewed). BCL11B, ETP-like and TLX3 are colored consistently with panel B, making the persistence of the two extremes and the shifting middle position of ETP-like directly visible. Ranks are descriptive and have no confidence intervals. Detailed definitions and full precision are in Supplementary Methods and Table S8; exploratory chromatin measurements are in Supplementary Figures S5 and S9."
)
a = s.index("## Figure legends\n")
b = s.index("## References", a)
s = s[:a] + main_legends + s[b:]
main.write_text(s, encoding="utf-8")
print(main)

supp_legends = r'''## Supplementary Figure S1. Normal-thymus sampling, complete stage profiles and coordinate-marker eligibility

(**A**) ZEB1-minus-ZEB2 balance for every reported normal-thymus stage in GSE142522, GSE195812, GSE206710 and Park/HTA, with stage order kept within each source. A point is a measured stage library or sample–stage aggregate, not an independent donor in every dataset; the sources are not pooled into one patient-level test. (**B**) Complete source-specific heatmap for ZEB1, ZEB2, LMO2 and LYL1 across the reported stages. Color is standardized within each gene and atlas for visualization, while unavailable measurements remain blank or explicitly marked. (**C**) Audit of the early-to-cortical direction of CD34, LYL1 and CD1A. A marker entered the frozen three-gene score only if the expected direction was observed in at least three normal resources where measured; outcome genes ZEB1 and ZEB2 and the candidate LMO2 were excluded. (**D**) GSE142522 CD8 single-positive ZEB2 recovery relative to preceding stages, documenting a nonmonotonic late feature. (**E**) The local GSE195812 immature-single-positive balance dip, shown without forcing a monotonic maturity curve. (**F**) ZEB1 expression in 15 Park/HTA donors with at least 20 cells in both DN and CD4 single-positive compartments; lines join stages from the same donor. (**G**) Source-level middle-minus-early marker contrasts, with plus, minus and missing signs retaining measurement availability; this panel explains the eligibility call in C. (**H**) Diagnostic-patient coordinate distribution against the measured normal-stage range. The 20 units defining that range are eight pooled FACS stage libraries and 12 sample–stage aggregates nested within three donors, not 20 donors. Normal-curve projection beyond that range is extrapolation; 14/18 BCL11B primary-cohort patients fall outside it.

## Supplementary Figure S2. Individual-gene subtype distributions and normal-reference boundary

(**A**) Individual ZEB1 values for all 1,309 diagnostic patients grouped into the 17 modern molecular subtypes; each dot is one patient, and quartile summaries do not replace the visible outliers. (**B**) ZEB2 values in exactly the same patients and subtype order, allowing constituent-gene patterns to be checked independently of their difference. (**C**) LMO2 values on the same biological units, displayed as a contextual T-lineage regulator rather than a component of the developmental score. (**D**) Cohort-standardized ZEB1-minus-ZEB2 balance for the same patients; this is the primary expression outcome. (**E**) Coordinates of all 18 BCL11B-subtype patients relative to the observed normal-stage domain, with 14 of 18 outside that domain. (**F**) Both residual definitions for those 18 patients: the primary cohort-internal observed-minus-fitted residual and the projection onto a separately standardized normal-thymus curve. Lines identify the same patient; different scales prohibit direct magnitude comparison. (**G**) Median residuals under the two definitions across all 17 subtypes; point size reflects subtype size, so small subtypes remain visible without receiving the same visual weight as large groups. (**H**) For every subtype, number and fraction of patients outside the normal-reference coordinate range, with numerators and denominators printed. The primary statistical inference uses the within-cohort spline, not normal-cell extrapolation.

## Supplementary Figure S3. Lim patient eligibility, technical handling and Day-28 null boundary

(**A**) Sample-flow audit distinguishing metadata patients, malignant biological samples, 54 eligible Day-0 whole-malignant pseudobulks, 41 paired ZBTB16-detection states and 12 paired Day-0/Day-28 patients. These denominators answer different questions and must not be interchanged. (**B**) Malignant blast counts for eligible Day-0 patient pseudobulks against the 50-cell minimum. Each mark is a biological sample, not a cell. (**C**) Positive- and negative-state malignant-cell counts for the 41 eligible within-sample pairs against the frozen 20-cell-per-state minimum. (**D**) Technical processing audit: integer UMI aggregation, L086 R1/R2 pooling before pseudobulk expression, omission of a duplicate P058 H5AD input while retaining the patient from the discovery source, and log₂(CPM + 1) expression. (**E**) Patient-connected Day-0 to Day-28 ZEB balance in the 12 longitudinal pairs; trajectories are shown even when they move against the group mean. (**F**) Leave-one-patient-out mean Day-28-minus-Day-0 balance, showing sensitivity to each paired patient. (**G**) Recomputed eligibility at 30, 50 and 100 malignant-blast thresholds using the fixed balance definition; these thresholds are post hoc checks, not new optimized cutoffs. (**H**) Pseudobulk library size versus balance, to reveal possible library-depth dependence. (**I**) Mean paired Day-28-minus-Day-0 change in ZEB1, ZEB2, LMO2 and balance with bootstrap 95% intervals. The balance effect is −0.23 (95% CI −0.77 to 0.30; paired Wilcoxon P = 0.569), so no reproducible treatment-selection effect is inferred.

## Supplementary Figure S4. Complete independent GSE146901 expression audit

(**A**) Display matrix for all 22 source RNA samples: eight ETP T-ALL, ten non-ETP T-ALL and four healthy peripheral T-cell samples. Rows are ZEB1, ZEB2, standardized balance and log₂ expression ratio; each metric is standardized separately for the heatmap, and column annotations retain the original group assignment. The peripheral controls are not thymocytes. (**B**) Individual sample values for the four metrics in their original analysis units, showing the extent of within-group heterogeneity and the sample with extreme ETP balance. Dots, rather than cells within a sample, are the independent units. (**C**) ETP-minus-non-ETP median differences and two-sided Mann–Whitney P values. Balance and ratio reproduce polarity (P = 0.012 and 0.016), whereas the two single-gene comparisons do not cross nominal P < 0.05. This is a replication of the ETP contrast, not of the 17-subtype developmental-residual ranking.

## Supplementary Figure S5. Chromatin assay QC and negative cross-assay comparisons

(**A**) Total filtered contacts for ten usable HiChIP libraries, separated by ETP, non-ETP, CD34-positive and thymus context. A second thymus archive, THY-2124, failed source-archive QC and is excluded rather than assigned zero contacts. (**B**) Depth-normalized ZEB1 and ZEB2 gene-body-associated contact counts in each usable library; each point or paired mark is one library. Contact frequency is not gene expression. (**C**) Analogous promoter-window contact counts, retained separately from gene-body contacts because proximity does not prove transcriptional action. (**D**) ZEB-locus peak measures in seven primary/PDX scATAC peak sets. These sets do not independently reproduce the reciprocal HiChIP ratio, and primary and PDX sources are identified rather than pooled as biological replicates. (**E**) Pooled GSE146901 loop-call rates for each ZEB locus and its ±1-Mb window. Pooled calls are not independent patient-level measurements and do not show the reciprocal 3D polarity suggested by the small HiChIP series. The detailed eight-panel HiChIP display is retained in Figure S9.

## Supplementary Figure S6. Complete BCL11B-rearranged case audit

(**A**) ZEB1 and ZEB2 gene abundance in each of the 12 GSE162280 case libraries, with lines joining the two genes within a case. Raw assigned counts, CPM, depth, rearrangement partner and phenotype are provided in Table S6. (**B**) Each case's log₂(ZEB1/ZEB2) by lesion group; all 12 values are below zero. Five cases have a direct ZEB2 fusion and seven have another enhancer partner, so the latter group cannot be attributed to a direct ZEB2 fusion call. (**C**) Case-level ratios separated into ZEB2-fusion (5), ARID1B-enhancer (5) and CDK6-enhancer (2) groups. Group summaries show observed distribution rather than a comparison with an unavailable ordinary T-ALL control. (**D**) Ratio plotted against assigned library counts, with reported AML, MPAL, ETP-ALL or unspecified presentation. The disease mix and potential fusion-related transcript quantification limit causal or T-ALL-specific inference. This series tests within-lesion partner convergence only.

## Supplementary Figure S7. Historical bulk-expression context and meta-analytic sensitivity

(**A**) Study-level Hedges g with 95% intervals for the three scoped contrasts across four older expression resources: higher ZEB1 in TLX-class cases, lower LMO2 in TLX-class cases and lower ZEB2 in TAL-class cases. Each study remains a separate unit; historical TLX/TAL labels are not interchangeable with the 17 modern genomic subtypes. (**B**) Pooled estimates under DerSimonian–Laird and REML with modified Hartung–Knapp uncertainty. The latter interval for TLX-class ZEB1 includes zero, so only bounded directional support is claimed. (**C**) Leave-one-cohort-out DerSimonian–Laird estimates for the same contrasts, exposing the influence of any single historical cohort. No HOXA or full subtype-residual replication claim is made.

## Supplementary Figure S8. Clinical attenuation and Lim response sensitivity

(**A**) Induction-failure odds ratio per one-unit higher diagnostic balance under an unadjusted model, 17-subtype adjustment and additional age/sex/white-cell-count adjustment, with 95% intervals. (**B**) The same three-model sequence for MRD ≥0.1%. (**C**) The same sequence for MRD ≥0.01%; separate testing thresholds are retained and receive six-endpoint Benjamini–Hochberg correction within each model level. (**D**) Event-free and overall-survival hazard ratios across the same adjustment sequence. Rare-subtype coefficients approached infinite estimates in the full Cox fits, so these survival associations remain exploratory despite displayed intervals. (**E**) All six fully adjusted endpoints in one forest display; filled symbols indicate six-endpoint BH FDR < 0.05, not validated prediction. (**F**) Lim Day-0 induction-failure-minus-responsive balance mean difference with patient-bootstrap 95% intervals in combined, discovery and extension analyses; the extension interval crosses zero. (**G**) Separate Lim unadjusted, broad-subtype, age and ETP sensitivity models. Each adds one covariate block to the baseline association, rather than forming a cumulative sequence; the ETP-adjusted interval includes zero. (**H**) Day-28 paired-balance null boundary in 12 patients. These panels display association and attenuation only; no cutoff, calibration, external prediction or mediation analysis was performed.

## Supplementary Figure S9. Exploratory HiChIP context formerly shown as main Figure 7

(**A**) Filtered-contact depth in the ten usable HiChIP libraries: four non-ETP T-ALL, three ETP, two CD34-positive and one usable thymus library. Depth is shown because contact ratios can be sensitive to library coverage. (**B**) Depth-normalized ZEB1 gene-body contacts by biological context; points represent libraries rather than patients in a prospective validation set. (**C**) ZEB2/ZEB1 gene-body contact ratio for the same libraries; a ratio is a structural contact measure, not evidence that either gene changed transcription. (**D**) Ordered leukemia ratios show all three ETP samples above all four non-ETP samples. With n = 3 versus n = 4, the exact two-sided Mann–Whitney P = 0.057 is the minimum possible under complete rank separation, not evidence meeting a conventional 0.05 threshold. (**E**) Paired ZEB1 and ZEB2 locus contacts within each library, preserving individual sample heterogeneity. (**F**) Promoter-window contact measures, examined separately from gene-body contacts. (**G**) Pooled GSE146901 loop rates fail to reproduce reciprocal contact polarity and do not provide independent patient replicates. (**H**) Seven scATAC peak sets likewise fail to replicate the HiChIP ratio across assays. Figure S5 provides the companion assay-depth and exclusion audit. No replicated chromatin mechanism is inferred.

'''
s = supp.read_text(encoding="utf-8")
a = s.index("## Supplementary Figure S1.")
b = s.index("## Supplementary Tables S1–S8", a)
s = s[:a] + supp_legends + s[b:]
supp.write_text(s, encoding="utf-8")
print(supp)
