"""Align frozen editorial prose with the final visual panel inventory."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
BASE = ROOT / 'submission/_build/editorial_rebuild'

# Re-running after main legends are synchronized still refreshes supplementary
# legends without applying one-time main-text replacements twice.
if '**A**, Cross-cohort validation matrix' in (
    BASE / 'Editorial_Figure_Legends.md').read_text(encoding='utf-8'):
    source = Path(__file__).read_text(encoding='utf-8')
    exec(compile(source[source.rindex('\nsupp = [') + 1:], str(__file__), 'exec'),
         {'BASE': BASE})
    raise SystemExit


def change(path, replacements):
    s = path.read_text(encoding='utf-8')
    for old, new in replacements:
        if old not in s:
            raise AssertionError(f'Missing text in {path.name}: {old[:90]}')
        s = s.replace(old, new)
    path.write_text(s, encoding='utf-8')


main_legend = BASE / 'Editorial_Figure_Legends.md'
change(main_legend, [
    ('The full eligibility set contained 24,356 genes. **B**',
     'The full eligibility set contained 24,356 genes; a small inset shows the measured selection counts as a true branching flow. **B**'),
    ('**D**, Frozen program scores from five normal Yayon donors',
     '**D**, Inset within E: frozen program scores from five normal Yayon donors'),
    ('**C**, Original versus group-excluded frozen-set membership after BCL11B and ETP-like patients were withheld during gene-set derivation. Of 50 genes per side, 39 ZEB1-side and 29 ZEB2-side genes were shared; the flanking segments show genes found only in the original or rederived set.',
     '**C**, Two literal two-set Venn diagrams compare each original 50-gene frozen set with the set rederived after BCL11B and ETP-like patients were withheld during gene selection. The ZEB1-side intersection has 39 genes, with 11 original-only and 11 rederived-only genes; the ZEB2-side intersection has 29, with 21 on each nonoverlapping side.'),
    ('separately fitted adult residual $R$ (number and lollipop), ZEB1-side score and ZEB2-side score (colored tiles; signed values printed)',
     'separately fitted adult residual $R$ (number and lollipop), adult balance $B$, ZEB1-side score, ZEB2-side score and ETP-like call (colored tiles and values)'),
])

text = main_legend.read_text(encoding='utf-8')
start = text.index('**A**, Evidence strip indicating', text.index('### Figure 5.'))
end = text.index('\n\n### Figure 6.', start)
replacement = '''**A**, Cross-cohort validation matrix for GSE146901, GSE234608, GSE243914, author-defined malignant cells in GSE248287 and adult GSE280250. Rows encode distinct assay contexts and biological units; columns show recovered-gene counts, expected-direction fractions and gene-effect correlation. These independent cohorts are not pooled into a single effect estimate. **B**, Three-cohort effect matrix for ordinary bulk GSE146901, ETP/MPAL bulk GSE234608 and blast-enriched GSE243914. Rows are cohorts and columns are the locked ZEB1-side score, ZEB2-side score and raw balance. Signed group differences and uncertainty are shown in the cells; the groups follow each source study's author labels. Blast enrichment does not ensure malignant-cell purity. **C**, Bubble forest of gene-level preservation in the five contexts from A. Horizontal position encodes effect-vector Spearman correlation; point area encodes recovered frozen genes and fill intensity encodes expected-direction fraction. The fractions/correlations are 87%/0.60, 80%/0.64, 91.8%/0.77, 77.7%/0.62 and 98.7%/0.86 in row order. Recovered and effect-tested denominators differ and are detailed in Table S7. **D**, Separate patient-level scatter panels for the ZEB1-side and ZEB2-side frozen scores against balance in 15 author-labelled malignant-cell pseudobulks. Spearman $\\rho=+0.73$ for ZEB1-side and $-0.21$ for ZEB2-side; the latter interval includes zero. Each patient is one independent unit. **E**, Ninety-four recovered frozen genes shown as a discovery-versus-malignant effect matrix. Rows retain frozen-side and rank identities; column values are scaled within their own context for visual comparison and should not be interpreted as directly comparable effect sizes. The weaker ZEB2-side patient-score result remains a boundary on malignant-cell interpretation. Source-level detail appears in Figures S6 and S8.'''
text = text[:start] + replacement + text[end:]
start = text.index('**A**, Frozen program scores', text.index('### Figure 6.'))
end = text.index('\n\n### Figure 7.', start)
replacement = '''**A**, Donor-by-lineage matrices of frozen ZEB1-side and ZEB2-side scores in GSE253355 normal marrow, with 12 donor rows and HSPC, CLP, T and myeloid columns wherever the primary minimum-20-cell eligibility criterion was met. Missing donor–lineage units remain grey. Heatmap color is a score, not the number of cells. **B**, Within-donor ZEB2-side differences relative to T cells, showing every eligible myeloid, HSPC and CLP comparison. Myeloid exceeded T in 12/12, HSPC in 11/11 and CLP in 0/8 donors; donor, not cell, is the independent unit. **C**, For 93 recovered frozen genes, normal myeloid-minus-T expression change versus the negative pediatric leukemia residual coefficient. Seventy-five percent aligned with the expected ZEB2-side direction, with descriptive Spearman $\\rho=0.60$. This establishes lineage affinity, not myeloid cell origin. **D**, Primary frozen-gene residual coefficients versus coefficients adjusted for marrow versus peripheral-blood specimen in the 1,309-patient cohort (928 marrow, 381 blood). All 100 retained sign and the effect-vector rank correlation was 0.9995. **E**, Forty-eight recoverable ZEB2-side genes across four independent leukemia contexts as a measured rectangular heatmap. Forty-five genes were normal-myeloid-concordant and three (AOAH, MAP3K5, ADRB2) were not; the latter names are printed beside their rows. Each cohort column is oriented so positive color means the expected ZEB2-side association. This decomposition, alongside blast-enriched and author-malignant observations, argues against passive admixture as the sole source of the signal; it does not prove a cell-intrinsic mechanism. Eligibility and threshold checks appear in S7.'''
text = text[:start] + replacement + text[end:]
start = text.index('**A**, Diagnostic GSE280250', text.index('### Figure 7.'))
replacement = '''**A**, Each of 79 author-designated adult-series GSE280250 diagnostic patients placed by balance $B$ and developmental-expression proxy $D$. The adult spline and residual $R$ were fitted anew in this cohort; pediatric residuals were not transported. **B**, Frozen ZEB1-side score against adult residual, one point per patient (Spearman $\\rho=+0.60$, bootstrap 95% CI +0.43 to +0.73). **C**, Frozen ZEB2-side score against adult residual ($\\rho=-0.66$, 95% CI −0.76 to −0.52). A small inset compares both correlations across all 79 patients, 72 aged at least 18 years and 70 aged at least 21 years; seven author-designated adult-series cases were younger than 18. **D**, Discovery-versus-adult residual-associated gene coefficients for the 78 genes eligible for both effect models. Eighty-six of 100 frozen genes were recovered, 98.7% of effect-tested genes had the expected sign and the gene-effect Spearman correlation was 0.86. The diagonal is an equal-effect visual reference, not a fitted line. **E**, Patient-level residual distributions by every high-confidence ALLCatchR2 main-cluster group, with 11 cases lacking a main call and three with multiple high-confidence main calls retained as explicit categories. Right-hand annotations show group size and the fraction with an ETP-like immature call; a main-cluster call and immature call can coexist. BCL11B ($n=7$) and TLX3-immature ($n=2$) are highlighted as context, not a complete independent 17-subtype ranking. **F**, Frozen 100-gene heatmap across eight measured contexts: pediatric discovery residual association, normal-thymus early-to-DP change, normal-marrow myeloid-to-T change, three external leukemia contrasts, author-labelled malignant-cell gene–balance association and adult residual association. Rows preserve original frozen side and rank. Left annotations encode frozen side, normal-development class and normal-myeloid class. The three ETP contrast columns were sign-reversed so positive denotes the non-ETP/T-ALL direction; normal columns retain their prespecified biological direction. Each context column was divided by its own 90th percentile absolute effect and clipped to $[-1,1]$ for display, so color magnitude cannot be compared across columns. Grey is unavailable. The matrix summarizes directional portability without implying a shared mechanism.'''
text = text[:start] + replacement + '\n'
main_legend.write_text(text, encoding='utf-8')

supp = [
('Normal-thymus data and spatial eligibility audit', '''**A**, Six-resource atlas-by-developmental-window coverage matrix. Filled Yayon cells represent source annotations; pale bulk cells are broad stage mappings and do not claim exact equivalence to the pediatric single-cell state labels. Assay labels identify bulk, CITE-seq and spatial resources. **B**, All 33 available Yayon author states by median balance $B$, developmental-expression proxy $D$, cell2location corticomedullary position, cell support and donor support. Each column was standardized separately for this matrix; grey CMA tiles are unavailable, not zero. States are ordered for audit, not as a newly inferred pseudotime. **C**, Three fixed proxy markers (CD34, LYL1 and CD1A) across the four normal bulk resources; tile color represents the source-specific middle-minus-early expression change and grey denotes an unavailable comparison. Outcome genes ZEB1 and ZEB2 were excluded from the proxy. **D**, Direct detection fraction of five selected genes across all 16 Visium libraries, restricted to spots where the source cell2location T-state abundance was at least half of total assigned abundance. ZEB2 exceeded the prespecified 10%-of-spots gate in only 2/16 libraries, preventing a direct spot-level ZEB2 spatial-expression claim. The cell2location state positions in Figure 1 are a separate analysis.'''),
('Developmental-proxy and residual-model robustness', '''**A**, Shared-baseline and leave-one-subtype-out median residuals for each of 17 molecular subtypes. In the latter analysis the evaluated subtype contributes no patient to its own expected spline; different held-out subtypes therefore have different training baselines. **B**, Heatmap of all 17 subtype residual ranks under the original three-gene proxy, three leave-one-marker-out proxies and an expanded prespecified expression score. Rank 1 is the most ZEB2-skewed; outlined BCL11B and TLX3 rows retain their major directional poles while middle ranks may move. **C**, Raw, adjusted and repeated five-fold patient-level cross-validated $R^2$ for proxy-only, subtype-only and combined models. The common patient set and held-out folds address the different model parameter counts. **D**, Median residuals for BCL11B, ETP-like and TLX3 when the natural spline degrees of freedom are fixed at 2, 3 or 4. No setting was selected by appearance or significance. **E**, Primary versus batch-adjusted coefficients for the 100 frozen genes; all preserve sign, a within-cohort sensitivity rather than replication. **F**, Diagnostic-patient and normal-reference proxy distributions; the normal domain is based on 20 stage units, consisting of eight pooled libraries and 12 sample–stage units nested in three donors, not 20 independent donors. Fourteen of 18 BCL11B patients fall outside that measured reference domain; primary residuals remain cohort-internal.'''),
('AIEOP classifier and pediatric external audit', '''**A**, Sample counts across all 16 official AIEOP molecular classes in 120 patients. **B**, Genuine patient-count alluvial showing the 33 fusion-anchored cases from known anchor category to official classifier-assigned subtype; ribbon widths are numbers of patients and all 33 tested anchor labels matched. This does not validate every assignment in the 120-patient dataset or define a new classifier threshold. **C**, Linked discovery-to-AIEOP median residuals in six comparable classes with at least five external patients. Lines connect subtype summaries, not paired individuals; smaller classes do not enter the six-class ordering statistic. **D**, Source official-assignment probabilities for the 33 anchored cases, displayed without a new optimized cutoff. The external cohort offers broad architectural support and does not reproduce all 17 discovery subtype ranks.'''),
('Frozen-program derivation and held-out robustness', '''**A**, Genome-wide residual coefficient versus partial $R^2$ for the 24,356 discovery-eligible genes. The 100 frozen genes are colored by side; 3,560 genes passed the locked FDR and coefficient gates before the two 50-gene sets were chosen by partial $R^2$. **B**, Binary gene-membership matrix for original and BCL11B/ETP-like-held-out derivations. Each row is a measured gene in the set union and each column indicates inclusion; the section break separates ZEB2 and ZEB1 sides. The original and rederived sides overlap by 29/50 and 39/50 genes, respectively. **C**, Competitive CAMERA evidence of the held-out-derived sets in the 18 fixed matched pairs. Patients were withheld from derivation but remain within the discovery cohort; the ZEB2-side result is stronger than the ZEB1-side result. **D**, Density of primary versus PC1–5-adjusted gene t statistics. Principal components may absorb biological signal, so the weak rank concordance is an overadjustment diagnostic and is not counted as a robustness success.'''),
('BCL11B matching and lesion case audit', '''**A**, Bipartite display of all 18 fixed BCL11B-to-ETP-like matches. Each connector is one patient pair, with opacity encoding the absolute developmental-proxy distance; no pairing is selected visually. **B**, The same pairs shown by cohort-internal residual, preserving patient connection and visibly including pairs that oppose the mean direction. The mean BCL11B-minus-ETP-like difference was −1.92 with a 3,000-bootstrap 95% interval from −2.98 to −0.67. **C**, Pair-blocked Hallmark CAMERA results displayed as a bubble plot: horizontal position is $-\\log_{10}$ BH FDR, point area is set size and color is the observed aggregate direction. These correlated signatures describe transcriptomic context, not activated pathways or causal ZEB targets. **D**, Full 12-case lesion matrix. Rows identify case and phenotype; columns show ZEB1 and ZEB2 CPM and their $\\log_2$ ratio, with fusion versus enhancer class at right. All ratios are negative, including seven cases without ZEB2 as a rearrangement partner. This AML/MPAL/ETP-ALL series has no ordinary T-ALL control.'''),
('Cross-cohort constituent-gene preservation', '''**A**, Lower-triangle Spearman correlations between six frozen-gene effect vectors—pediatric residual association, three external leukemia contrasts, author-labelled malignant-cell association and adult residual association. Upper-triangle cells give the number of genes measurable in each pair; assay contrasts are oriented to the same leukemia-side sign before correlation. Pairwise missingness means the shared-gene denominator varies. **B**, Gene-by-gene discovery-versus-blast-enriched effect comparison for GSE243914, with frozen side and sign retained. **C**, The equivalent discovery-versus-author-malignant effect comparison; patients, not single cells, formed the malignant pseudobulk units. **D**, Discovery-versus-adult effect comparison, again limited to genes tested in both contexts. These effect plots audit the summary fractions in Figure 5 and do not require each gene to reach an individual P-value threshold.'''),
('Normal-marrow lineage resolution', '''**A**, ZEB2-side frozen score in every eligible donor-by-broad-lineage normal-marrow pseudobulk under the primary minimum-20-cell rule. Grey cells lack an eligible donor–lineage unit. **B**, Ninety-three measured frozen genes by the median expression of HSPC, CLP, T and myeloid units; each gene is row-standardized for display and arranged by original frozen side and rank. This is not a new gene-selection analysis. **C**, Every within-donor myeloid-minus-T, HSPC-minus-T and CLP-minus-T ZEB2-side difference. The denominator is donor pairs (12, 11 and eight), not individual cells. **D**, Median lineage scores under minimum-20 and minimum-10 eligible-cell gates using the same frozen genes. The similar broad pattern does not identify a leukemia cell of origin. The 45-plus-three-gene decomposition in Figure 6E remains a descriptive split.'''),
('Author-defined malignant cells and Lim boundaries', '''**A**, Fifteen author-labelled GSE248287 malignant patient pseudobulks by balance and the two frozen program scores. Rows are patients ordered by measured balance; each matrix column uses its displayed score scale. **B**, Two separate patient-level scatter plots relate the ZEB1-side and ZEB2-side scores to balance. The ZEB1-side correlation is +0.73; ZEB2-side is −0.21 and its interval spans zero. **C**, Malignant-cell counts for all 15 patients. The independent biological unit in A and B remains the patient. **D**, Forty-one within-patient Lim Day-0 ZBTB16-detected versus undetected malignant-state pairs, showing every paired balance rather than only an aggregate effect. ZBTB16 is an operational state label, not a causal or developmental-stage assignment. **E**, Twelve eligible patient-connected Day-0 to Day-28 trajectories. The mean change was −0.23 (95% interval −0.77 to +0.30; paired Wilcoxon P=0.569); no reproducible treatment-selected ZEB state is inferred. The 54 Day-0, 41 state-pair and 12 longitudinal denominators answer different questions.'''),
('Adult subtype context', '''**A**, Three-layer alluvial for all 79 GSE280250 author-designated adult-series patients: official ALLCatchR2 high-confidence main-cluster category, overlapping ETP-like immature call and adult-cohort residual display bin. Ribbon width is patient count. The display bins $R<-0.5$, $-0.5\\leq R\\leq0.5$ and $R>0.5$ are visual categories only, not biological or clinical classifiers. Multiple and absent high-confidence main calls are retained. **B**, Patient counts for every main-cluster category, including multiple-call and no-call categories. **C**, Age against adult-cohort residual, showing the full author adult series and the younger-than-18 subset without relabeling the source cohort. **D**, Patient residuals by ETP-like immature-call status with individual points and summary medians. The ALLCatchR2 calls are classifier context on the same adult dataset, not a second independent validation cohort.'''),
('Perturbational, chromatin and clinical boundaries', '''**A**, Three paired donor EV-to-acute-BCL11B-overexpression measurements in CD34-positive cells for $\\log_2(\\mathrm{ZEB1}/\\mathrm{ZEB2})$, ZEB1, ZEB2 and developmental proxy. Every donor line is retained; the direction does not reproduce the lesion-associated ZEB2-side state. This brief perturbation is not a model of chronic leukemia. **B**, Genomic-locus-style tracks for ZEB1 and ZEB2 from six source GRCh38 narrowPeak files: four BCL11B tracks and two H3K27ac tracks. Rectangles are measured peaks, with height scaled within each track; the transcription start and promoter window are marked. Promoter occupancy is assay and sample specific, and peak height is not directly comparable between tracks. **C**, Measured ChIP and H3K27ac promoter/body peak-hit counts. HiChIP, pooled-loop and scATAC rows are marked unavailable for this *same promoter/body peak-hit readout*, not negative peak counts; their separate analyses did not independently reproduce a shared chromatin polarity. HiChIP used three ETP and four non-ETP libraries, with complete rank separation but minimum attainable exact two-sided P=0.057. **D**, Six clinical endpoints as unadjusted and molecular-subtype-adjusted odds/hazard ratios with 95% intervals. Open EFS/OS marks flag sparse-subtype Cox convergence warnings; those results are retained for audit and are not inferential survival claims. Binary associations attenuate after subtype adjustment. Full covariate/ridge sensitivities and warnings remain in Table S10; no predictive cutoff or clinical utility is claimed.'''),
]

supp_text = '\n\n'.join(f'## Supplementary Figure S{i}. {title}\n\n{body}'
                        for i, (title, body) in enumerate(supp, 1)) + '\n'
(BASE / 'Editorial_Supplement_Legends.md').write_text(supp_text, encoding='utf-8')
